/**
 * Simple order API
 * This is a simple Order API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Order { 
    name?: string;
    adress?: string;
    town?: string;
    zipcode?: string;
    products?: Array<number>;
}